// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

module.exports = function() {
  var World;
  World = this;
  this.Widgets = {};
  this.Widget = (function() {
    Widget.extend = function(protoProps, staticProps) {
      var Surrogate, child;
      if (Object.hasOwnProperty(protoProps, 'constructor')) {
        child = protoProps.constructor;
      } else {
        child = (function(_this) {
          return function() {
            return _this.apply(_this, arguments);
          };
        })(this);
      }
      child.copyProperties(this);
      child.copyProperties(staticProps);
      Surrogate = function() {
        this.constructor = child;
        return void 0;
      };
      Surrogate.prototype = this.prototype;
      child.prototype = new Surrogate();
      if (protoProps) {
        child.prototype.copyProperties(protoProps);
      }
      child.__super__ = this.prototype;
      return child;
    };

    function Widget(attributes) {
      if (attributes == null) {
        attributes = {};
      }
      _.extend(this, attributes);
    }

    Widget.prototype.world = World;

    Widget.getter('driver', function() {
      return this._driver || World.driver;
    });

    Widget.prototype.click = function(selector) {
      return this.find(selector).click();
    };

    Widget.prototype.fill = function(selector, value) {
      return this.find(selector).sendKeys(value);
    };

    Widget.prototype.read = function(selector) {
      var selected;
      selected = this.find(selector);
      return selected.getAttribute('value').then(function(value) {
        return value || selected.getText();
      });
    };

    Widget.prototype.find = function(selector) {
      var _isPresent, _selector;
      _selector = Driver.By.css(this._selector(selector));
      _isPresent = (function(_this) {
        return function() {
          return _this.driver.isElementPresent(_selector);
        };
      })(this);
      this.driver.wait(_isPresent, 10000, "" + _selector + " not found");
      return this.driver.findElement(_selector);
    };

    Widget.prototype.isPresent = function() {
      return this.driver.isElementPresent(Driver.By.css(this.root));
    };

    Widget.prototype.findAll = function(selector) {
      return this.driver.findElements(Driver.By.css(this._selector(selector)));
    };

    Widget.prototype._selector = function(selector) {
      return this.root + (selector ? " " + selector : '');
    };

    Widget.prototype._map = function(collection, callback) {
      var results, _reduce;
      results = [];
      _reduce = function(p, f, i) {
        return p.then(function() {
          return callback(f, i).then(function(v) {
            return results.push(v);
          });
        });
      };
      return _.reduce(collection, _reduce, Driver.promise.fulfilled()).then(function() {
        return results;
      });
    };

    return Widget;

  })();
  this.Widget.Fields = (function(_super) {
    __extends(Fields, _super);

    function Fields() {
      return Fields.__super__.constructor.apply(this, arguments);
    }

    Fields.prototype.fillAll = function(values) {
      return this._map(this.fields, (function(_this) {
        return function(f) {
          return _this.fill(_this._name(f), values[f]);
        };
      })(this));
    };

    Fields.prototype.readAll = function() {
      var _readAll;
      _readAll = (function(_this) {
        return function(f) {
          return _this.read(_this._name(f)).then(function(v) {
            return [f, v];
          });
        };
      })(this);
      return this._map(this.fields, _readAll).then(function(read) {
        return _.object(read);
      });
    };

    Fields.prototype._name = function(name) {
      return "[name='" + name + "']";
    };

    Fields.prototype._type = function(type) {
      return "[type='" + type + "']";
    };

    return Fields;

  })(this.Widget);
  this.Widget.Form = (function(_super) {
    __extends(Form, _super);

    function Form() {
      this.submitWith = __bind(this.submitWith, this);
      return Form.__super__.constructor.apply(this, arguments);
    }

    Form.prototype.submitSelector = function() {
      return this._type('submit');
    };

    Form.prototype.submitWith = function(values) {
      this.fillAll(values);
      return this.click(this.submitSelector());
    };

    return Form;

  })(this.Widget.Fields);
  return this.Widget.List = (function(_super) {
    __extends(List, _super);

    function List() {
      return List.__super__.constructor.apply(this, arguments);
    }

    List.prototype.itemSelector = 'li';

    List.prototype.itemClass = World.Widget;

    List.prototype.items = function() {
      return this.findAll(this.itemSelector).then((function(_this) {
        return function(items) {
          return _.map(items, function(item, i) {
            var sel;
            sel = "" + _this.root + " " + _this.itemSelector + ":nth-child(" + (i + 1) + ")";
            return new _this.itemClass({
              root: sel
            });
          });
        };
      })(this));
    };

    return List;

  })(this.Widget);
};
