// Generated by CoffeeScript 1.7.1
module.exports = function(lib) {
  process.argv.push("--require");
  process.argv.push("" + lib + "/support");
  process.argv.push("--require");
  process.argv.push("features");
  require('./environment')();
  return require(require.resolve('cucumber').replace(/lib\/cucumber\.js$/, 'bin/cucumber.js'));
};
