// Generated by CoffeeScript 1.7.1
var __slice = [].slice;

module.exports = function() {
  var chai, copyProperties, origDescriptor;
  global.Driver = require('selenium-webdriver');
  global._ = require('lodash');
  global.$ = Driver.promise;
  origDescriptor = function(source, prop) {
    if (!source) {
      return nil;
    }
    return Object.getOwnPropertyDescriptor(source, prop) || origDescriptor(Object.getPrototypeOf(source), prop);
  };
  copyProperties = function(obj, source) {
    var prop;
    for (prop in source) {
      Object.defineProperty(obj, prop, origDescriptor(source, prop));
    }
    return obj;
  };
  Object.defineProperties(Object.prototype, {
    includes: {
      value: function(mixin) {
        copyProperties(this, mixin);
        copyProperties(this.prototype, mixin.prototype);
        return this;
      }
    },
    getter: {
      value: function(object, property, getter) {
        var _ref;
        if (!getter) {
          _ref = [this.prototype, object, property], object = _ref[0], property = _ref[1], getter = _ref[2];
        }
        return Object.defineProperty(object, property, {
          configurable: true,
          enumerable: true,
          get: getter
        });
      }
    },
    setter: {
      value: function(object, property, setter) {
        var getter, _ref;
        if (!setter) {
          _ref = [this.prototype, object, property], object = _ref[0], property = _ref[1], getter = _ref[2];
        }
        return Object.defineProperty(object, property, {
          configurable: true,
          enumerable: true,
          set: getter
        });
      }
    },
    accessor: {
      value: function(object, property) {
        var _ref;
        if (!property) {
          _ref = [this.prototype, object], object = _ref[0], property = _ref[1];
        }
        return Object.defineProperty(object, property, {
          configurable: true,
          enumerable: true,
          get: function() {
            return this["_" + property];
          },
          set: function(v) {
            return this["_" + property] = v;
          }
        });
      }
    }
  });
  chai = require('chai');
  chai.use(require('chai-as-promised'));
  chai.should();
  Object.defineProperty($.Promise.prototype, 'should', {
    get: Object.prototype.__lookupGetter__('should')
  });
  Object.defineProperties(Object.prototype, {
    $: {
      value: function() {
        var args, deferred, fn, _ref;
        fn = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
        deferred = $.defer();
        (_ref = (_.isFunction(fn) ? fn : this[fn])).call.apply(_ref, [this].concat(__slice.call(args), [function() {
          var error, results;
          error = arguments[0], results = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
          if (error) {
            return deferred.reject(error);
          } else {
            return deferred.fulfill.apply(deferred, results);
          }
        }]));
        return deferred.promise;
      }
    }
  });
  if (process.env.CHROMEDRIVER_PORT) {
    return require('../node_modules/selenium-webdriver/chrome').ServiceBuilder.prototype.port_ = process.env.CHROMEDRIVER_PORT;
  }
};
